/** ISO 3166-1 country names with E.164 dial codes for contact form autocomplete. */
export const WORLD_COUNTRIES_DATA = [
  { dialCode: '+93', name: 'Afghanistan' },
  { dialCode: '+355', name: 'Albania' },
  { dialCode: '+213', name: 'Algeria' },
  { dialCode: '+376', name: 'Andorra' },
  { dialCode: '+244', name: 'Angola' },
  { dialCode: '+1', name: 'Antigua and Barbuda' },
  { dialCode: '+54', name: 'Argentina' },
  { dialCode: '+374', name: 'Armenia' },
  { dialCode: '+61', name: 'Australia' },
  { dialCode: '+43', name: 'Austria' },
  { dialCode: '+994', name: 'Azerbaijan' },
  { dialCode: '+1', name: 'Bahamas' },
  { dialCode: '+973', name: 'Bahrain' },
  { dialCode: '+880', name: 'Bangladesh' },
  { dialCode: '+1', name: 'Barbados' },
  { dialCode: '+375', name: 'Belarus' },
  { dialCode: '+32', name: 'Belgium' },
  { dialCode: '+501', name: 'Belize' },
  { dialCode: '+229', name: 'Benin' },
  { dialCode: '+975', name: 'Bhutan' },
  { dialCode: '+591', name: 'Bolivia' },
  { dialCode: '+387', name: 'Bosnia and Herzegovina' },
  { dialCode: '+267', name: 'Botswana' },
  { dialCode: '+55', name: 'Brazil' },
  { dialCode: '+673', name: 'Brunei' },
  { dialCode: '+359', name: 'Bulgaria' },
  { dialCode: '+226', name: 'Burkina Faso' },
  { dialCode: '+257', name: 'Burundi' },
  { dialCode: '+238', name: 'Cabo Verde' },
  { dialCode: '+855', name: 'Cambodia' },
  { dialCode: '+237', name: 'Cameroon' },
  { dialCode: '+1', name: 'Canada' },
  { dialCode: '+236', name: 'Central African Republic' },
  { dialCode: '+235', name: 'Chad' },
  { dialCode: '+56', name: 'Chile' },
  { dialCode: '+86', name: 'China' },
  { dialCode: '+57', name: 'Colombia' },
  { dialCode: '+269', name: 'Comoros' },
  { dialCode: '+242', name: 'Congo' },
  { dialCode: '+506', name: 'Costa Rica' },
  { dialCode: '+385', name: 'Croatia' },
  { dialCode: '+53', name: 'Cuba' },
  { dialCode: '+357', name: 'Cyprus' },
  { dialCode: '+420', name: 'Czechia' },
  { dialCode: '+225', name: "Côte d'Ivoire" },
  { dialCode: '+243', name: 'Democratic Republic of the Congo' },
  { dialCode: '+45', name: 'Denmark' },
  { dialCode: '+253', name: 'Djibouti' },
  { dialCode: '+1', name: 'Dominica' },
  { dialCode: '+1', name: 'Dominican Republic' },
  { dialCode: '+593', name: 'Ecuador' },
  { dialCode: '+20', name: 'Egypt' },
  { dialCode: '+503', name: 'El Salvador' },
  { dialCode: '+240', name: 'Equatorial Guinea' },
  { dialCode: '+291', name: 'Eritrea' },
  { dialCode: '+372', name: 'Estonia' },
  { dialCode: '+268', name: 'Eswatini' },
  { dialCode: '+251', name: 'Ethiopia' },
  { dialCode: '+679', name: 'Fiji' },
  { dialCode: '+358', name: 'Finland' },
  { dialCode: '+33', name: 'France' },
  { dialCode: '+241', name: 'Gabon' },
  { dialCode: '+220', name: 'Gambia' },
  { dialCode: '+995', name: 'Georgia' },
  { dialCode: '+49', name: 'Germany' },
  { dialCode: '+233', name: 'Ghana' },
  { dialCode: '+30', name: 'Greece' },
  { dialCode: '+1', name: 'Grenada' },
  { dialCode: '+502', name: 'Guatemala' },
  { dialCode: '+224', name: 'Guinea' },
  { dialCode: '+245', name: 'Guinea-Bissau' },
  { dialCode: '+592', name: 'Guyana' },
  { dialCode: '+509', name: 'Haiti' },
  { dialCode: '+504', name: 'Honduras' },
  { dialCode: '+36', name: 'Hungary' },
  { dialCode: '+354', name: 'Iceland' },
  { dialCode: '+91', name: 'India' },
  { dialCode: '+62', name: 'Indonesia' },
  { dialCode: '+98', name: 'Iran' },
  { dialCode: '+964', name: 'Iraq' },
  { dialCode: '+353', name: 'Ireland' },
  { dialCode: '+972', name: 'Israel' },
  { dialCode: '+39', name: 'Italy' },
  { dialCode: '+1', name: 'Jamaica' },
  { dialCode: '+81', name: 'Japan' },
  { dialCode: '+962', name: 'Jordan' },
  { dialCode: '+7', name: 'Kazakhstan' },
  { dialCode: '+254', name: 'Kenya' },
  { dialCode: '+686', name: 'Kiribati' },
  { dialCode: '+965', name: 'Kuwait' },
  { dialCode: '+996', name: 'Kyrgyzstan' },
  { dialCode: '+856', name: 'Laos' },
  { dialCode: '+371', name: 'Latvia' },
  { dialCode: '+961', name: 'Lebanon' },
  { dialCode: '+266', name: 'Lesotho' },
  { dialCode: '+231', name: 'Liberia' },
  { dialCode: '+218', name: 'Libya' },
  { dialCode: '+423', name: 'Liechtenstein' },
  { dialCode: '+370', name: 'Lithuania' },
  { dialCode: '+352', name: 'Luxembourg' },
  { dialCode: '+261', name: 'Madagascar' },
  { dialCode: '+265', name: 'Malawi' },
  { dialCode: '+60', name: 'Malaysia' },
  { dialCode: '+960', name: 'Maldives' },
  { dialCode: '+223', name: 'Mali' },
  { dialCode: '+356', name: 'Malta' },
  { dialCode: '+692', name: 'Marshall Islands' },
  { dialCode: '+222', name: 'Mauritania' },
  { dialCode: '+230', name: 'Mauritius' },
  { dialCode: '+52', name: 'Mexico' },
  { dialCode: '+691', name: 'Micronesia' },
  { dialCode: '+373', name: 'Moldova' },
  { dialCode: '+377', name: 'Monaco' },
  { dialCode: '+976', name: 'Mongolia' },
  { dialCode: '+382', name: 'Montenegro' },
  { dialCode: '+212', name: 'Morocco' },
  { dialCode: '+258', name: 'Mozambique' },
  { dialCode: '+95', name: 'Myanmar' },
  { dialCode: '+264', name: 'Namibia' },
  { dialCode: '+674', name: 'Nauru' },
  { dialCode: '+977', name: 'Nepal' },
  { dialCode: '+31', name: 'Netherlands' },
  { dialCode: '+64', name: 'New Zealand' },
  { dialCode: '+505', name: 'Nicaragua' },
  { dialCode: '+227', name: 'Niger' },
  { dialCode: '+234', name: 'Nigeria' },
  { dialCode: '+850', name: 'North Korea' },
  { dialCode: '+389', name: 'North Macedonia' },
  { dialCode: '+47', name: 'Norway' },
  { dialCode: '+968', name: 'Oman' },
  { dialCode: '+92', name: 'Pakistan' },
  { dialCode: '+680', name: 'Palau' },
  { dialCode: '+970', name: 'Palestine' },
  { dialCode: '+507', name: 'Panama' },
  { dialCode: '+675', name: 'Papua New Guinea' },
  { dialCode: '+595', name: 'Paraguay' },
  { dialCode: '+51', name: 'Peru' },
  { dialCode: '+63', name: 'Philippines' },
  { dialCode: '+48', name: 'Poland' },
  { dialCode: '+351', name: 'Portugal' },
  { dialCode: '+974', name: 'Qatar' },
  { dialCode: '+40', name: 'Romania' },
  { dialCode: '+7', name: 'Russia' },
  { dialCode: '+250', name: 'Rwanda' },
  { dialCode: '+1', name: 'Saint Kitts and Nevis' },
  { dialCode: '+1', name: 'Saint Lucia' },
  { dialCode: '+1', name: 'Saint Vincent and the Grenadines' },
  { dialCode: '+685', name: 'Samoa' },
  { dialCode: '+378', name: 'San Marino' },
  { dialCode: '+239', name: 'Sao Tome and Principe' },
  { dialCode: '+966', name: 'Saudi Arabia' },
  { dialCode: '+221', name: 'Senegal' },
  { dialCode: '+381', name: 'Serbia' },
  { dialCode: '+248', name: 'Seychelles' },
  { dialCode: '+232', name: 'Sierra Leone' },
  { dialCode: '+65', name: 'Singapore' },
  { dialCode: '+421', name: 'Slovakia' },
  { dialCode: '+386', name: 'Slovenia' },
  { dialCode: '+677', name: 'Solomon Islands' },
  { dialCode: '+252', name: 'Somalia' },
  { dialCode: '+27', name: 'South Africa' },
  { dialCode: '+82', name: 'South Korea' },
  { dialCode: '+211', name: 'South Sudan' },
  { dialCode: '+34', name: 'Spain' },
  { dialCode: '+94', name: 'Sri Lanka' },
  { dialCode: '+249', name: 'Sudan' },
  { dialCode: '+597', name: 'Suriname' },
  { dialCode: '+46', name: 'Sweden' },
  { dialCode: '+41', name: 'Switzerland' },
  { dialCode: '+963', name: 'Syria' },
  { dialCode: '+886', name: 'Taiwan' },
  { dialCode: '+992', name: 'Tajikistan' },
  { dialCode: '+255', name: 'Tanzania' },
  { dialCode: '+66', name: 'Thailand' },
  { dialCode: '+670', name: 'Timor-Leste' },
  { dialCode: '+228', name: 'Togo' },
  { dialCode: '+676', name: 'Tonga' },
  { dialCode: '+1', name: 'Trinidad and Tobago' },
  { dialCode: '+216', name: 'Tunisia' },
  { dialCode: '+90', name: 'Turkey' },
  { dialCode: '+993', name: 'Turkmenistan' },
  { dialCode: '+688', name: 'Tuvalu' },
  { dialCode: '+256', name: 'Uganda' },
  { dialCode: '+380', name: 'Ukraine' },
  { dialCode: '+971', name: 'United Arab Emirates' },
  { dialCode: '+44', name: 'United Kingdom' },
  { dialCode: '+1', name: 'United States' },
  { dialCode: '+598', name: 'Uruguay' },
  { dialCode: '+998', name: 'Uzbekistan' },
  { dialCode: '+678', name: 'Vanuatu' },
  { dialCode: '+379', name: 'Vatican City' },
  { dialCode: '+58', name: 'Venezuela' },
  { dialCode: '+84', name: 'Vietnam' },
  { dialCode: '+967', name: 'Yemen' },
  { dialCode: '+260', name: 'Zambia' },
  { dialCode: '+263', name: 'Zimbabwe' }
] as const;

export type WorldCountryName = (typeof WORLD_COUNTRIES_DATA)[number]['name'];

/** Sorted country names for combobox display. */
export const WORLD_COUNTRIES = WORLD_COUNTRIES_DATA.map((entry) => entry.name);

const DIAL_CODE_BY_COUNTRY = new Map<string, string>(
  WORLD_COUNTRIES_DATA.map((entry) => [entry.name, entry.dialCode])
);

export function getCountryDialCode(countryName: string): string {
  return DIAL_CODE_BY_COUNTRY.get(countryName) ?? '';
}
